#include "opcodes.h"

const int parameter_sizes[NUM_PARAMETER_KINDS] = {
    [T_NONE]     = 0,
    [T_IMED]     = 0,
    [T_ARGS]     = 0,
    [T_PUSH]     = 0,
    [T_VASTART]  = 0,
    [T_VAEND]    = 0,
    [T_DC]       = 0,
    [T_DWORD]    = 4,
    [T_WORD]     = 2,
    [T_BYTE]     = 1,
    [T_FLOAT]    = 4,
    [T_REG]      = 1,
    [T_BREG]     = 1,
    [T_DREG]     = 0, // ?
    [T_FUNC]     = 2,
    [T_FUNC2]    = 2,
    [T_V2]       = 0,
    [T_V3]       = 0,
    [T_V4]       = 0,
    [T_STR]      = VARIABLE_SIZED,
    [T_PFLAG]    = 2,
    [T_SWITCH]   = VARIABLE_SIZED,
    [T_SWITCH2B] = VARIABLE_SIZED,
    [T_DATA]     = 2,
    [T_STRDATA]  = 2
};

const OpcodeDefinition opcodes[NUM_OPCODES] = {
    {OP_NOP, "nop", {T_NONE, T_NONE}},
    {OP_RET, "ret", {T_NONE, T_NONE}},
    {OP_SYNC, "sync", {T_NONE, T_NONE}},
    {OP_EXIT, "exit", {T_ARGS, T_DWORD, T_NONE}},
    {OP_THREAD, "thread", {T_IMED, T_FUNC, T_NONE}},
    {OP_VA_START, "va_start", {T_VASTART, T_NONE, T_V3}},
    {OP_VA_END, "va_end", {T_VAEND, T_NONE, T_V3}},
    {OP_VA_CALL, "va_call", {T_IMED, T_FUNC, T_NONE, T_V3}},
    {OP_LET, "let", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_LETI, "leti", {T_IMED, T_REG, T_DWORD, T_NONE}},
    {OP_LETB, "letb", {T_IMED, T_REG, T_BYTE, T_NONE}},
    {OP_LETW, "letw", {T_IMED, T_REG, T_WORD, T_NONE}},
    {OP_LETA, "leta", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_LETO, "leto", {T_IMED, T_REG, T_FUNC, T_NONE}},
    {OP_SET, "set", {T_IMED, T_REG, T_NONE}},
    {OP_CLEAR, "clear", {T_IMED, T_REG, T_NONE}},
    {OP_REV, "rev", {T_IMED, T_REG, T_NONE}},
    {OP_GSET, "gset", {T_IMED, T_PFLAG, T_NONE}},
    {OP_GCLEAR, "gclear", {T_IMED, T_PFLAG, T_NONE}},
    {OP_GREV, "grev", {T_IMED, T_PFLAG, T_NONE}},
    {OP_GLET, "glet", {T_IMED, T_PFLAG, T_NONE}},
    {OP_GGET, "gget", {T_IMED, T_PFLAG, T_REG, T_NONE}},
    {OP_ADD, "add", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_ADDI, "addi", {T_IMED, T_REG, T_DWORD, T_NONE}},
    {OP_SUB, "sub", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_SUBI, "subi", {T_IMED, T_REG, T_DWORD, T_NONE}},
    {OP_MUL, "mul", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_MULI, "muli", {T_IMED, T_REG, T_DWORD, T_NONE}},
    {OP_DIV, "div", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_DIVI, "divi", {T_IMED, T_REG, T_DWORD, T_NONE}},
    {OP_AND, "and", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_ANDI, "andi", {T_IMED, T_REG, T_DWORD, T_NONE}},
    {OP_OR, "or", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_ORI, "ori", {T_IMED, T_REG, T_DWORD, T_NONE}},
    {OP_XOR, "xor", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_XORI, "xori", {T_IMED, T_REG, T_DWORD, T_NONE}},
    {OP_MOD, "mod", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_MODI, "modi", {T_IMED, T_REG, T_DWORD, T_NONE}},
    {OP_JMP, "jmp", {T_IMED, T_FUNC, T_NONE}},
    {OP_CALL, "call", {T_IMED, T_FUNC, T_NONE}},
    {OP_JMP_ON, "jmp_on", {T_IMED, T_FUNC, T_SWITCH2B, T_NONE}},
    {OP_JMP_OFF, "jmp_off", {T_IMED, T_FUNC, T_SWITCH2B, T_NONE}},
    {OP_JMP_EQ, "jmp_=", {T_IMED, T_REG, T_REG, T_FUNC, T_NONE}},
    {OP_JMPI_EQ, "jmpi_=", {T_IMED, T_REG, T_DWORD, T_FUNC, T_NONE}},
    {OP_JMP_NEQ, "jmp_!=", {T_IMED, T_REG, T_REG, T_FUNC, T_NONE}},
    {OP_JMPI_NEQ, "jmpi_!=", {T_IMED, T_REG, T_DWORD, T_FUNC, T_NONE}},
    {OP_UJMP_GT, "ujmp_>", {T_IMED, T_REG, T_REG, T_FUNC, T_NONE}},
    {OP_UJMPI_GT, "ujmpi_>", {T_IMED, T_REG, T_DWORD, T_FUNC, T_NONE}},
    {OP_JMP_GT, "jmp_>", {T_IMED, T_REG, T_REG, T_FUNC, T_NONE}},
    {OP_JMPI_GT, "jmpi_>", {T_IMED, T_REG, T_DWORD, T_FUNC, T_NONE}},
    {OP_UJMP_LT, "ujmp_<", {T_IMED, T_REG, T_REG, T_FUNC, T_NONE}},
    {OP_UJMPI_LT, "ujmpi_<", {T_IMED, T_REG, T_DWORD, T_FUNC, T_NONE}},
    {OP_JMP_LT, "jmp_<", {T_IMED, T_REG, T_REG, T_FUNC, T_NONE}},
    {OP_JMPI_LT, "jmpi_<", {T_IMED, T_REG, T_DWORD, T_FUNC, T_NONE}},
    {OP_UJMP_GTE, "ujmp_>=", {T_IMED, T_REG, T_REG, T_FUNC, T_NONE}},
    {OP_UJMPI_GTE, "ujmpi_>=", {T_IMED, T_REG, T_DWORD, T_FUNC, T_NONE}},
    {OP_JMP_GTE, "jmp_>=", {T_IMED, T_REG, T_REG, T_FUNC, T_NONE}},
    {OP_JMPI_GTE, "jmpi_>=", {T_IMED, T_REG, T_DWORD, T_FUNC, T_NONE}},
    {OP_UJMP_LTE, "ujmp_<=", {T_IMED, T_REG, T_REG, T_FUNC, T_NONE}},
    {OP_UJMPI_LTE, "ujmpi_<=", {T_IMED, T_REG, T_DWORD, T_FUNC, T_NONE}},
    {OP_JMP_LTE, "jmp_<=", {T_IMED, T_REG, T_REG, T_FUNC, T_NONE}},
    {OP_JMPI_LTE, "jmpi_<=", {T_IMED, T_REG, T_DWORD, T_FUNC, T_NONE}},
    {OP_SWITCH_JMP, "switch_jmp", {T_IMED, T_REG, T_SWITCH, T_NONE}},
    {OP_SWITCH_CALL, "switch_call", {T_IMED, T_REG, T_SWITCH, T_NONE}},
    {OP_STACK_PUSH, "stack_push", {T_IMED, T_REG, T_NONE}},
    {OP_STACK_POP, "stack_pop", {T_IMED, T_REG, T_NONE}},
    {OP_STACK_PUSHM, "stack_pushm", {T_IMED, T_REG, T_DWORD, T_NONE}},
    {OP_STACK_POPM, "stack_popm", {T_IMED, T_REG, T_DWORD, T_NONE}},
    {OP_ARG_PUSHR, "arg_pushr", {T_PUSH, T_REG, T_NONE, T_V3}},
    {OP_ARG_PUSHL, "arg_pushl", {T_PUSH, T_DWORD, T_NONE, T_V3}},
    {OP_ARG_PUSHB, "arg_pushb", {T_PUSH, T_BREG, T_NONE, T_V3}},
    {OP_ARG_PUSHW, "arg_pushw", {T_PUSH, T_WORD, T_NONE, T_V3}},
    {OP_ARG_PUSHA, "arg_pusha", {T_PUSH, T_REG, T_NONE, T_V3}},
    {OP_ARG_PUSHO, "arg_pusho", {T_PUSH, T_FUNC, T_NONE, T_V3}},
    {OP_ARG_PUSHS, "arg_pushs", {T_PUSH, T_STR, T_NONE, T_V3}},
    {OP_MESSAGE, "message", {T_ARGS, T_DWORD, T_STR, T_NONE}},
    {OP_LIST, "list", {T_ARGS, T_BREG, T_STR, T_NONE}},
    {OP_FADEIN, "fadein", {T_NONE, T_NONE}},
    {OP_FADEOUT, "fadeout", {T_NONE, T_NONE}},
    {OP_SE, "se", {T_ARGS, T_DWORD, T_NONE}},
    {OP_BGM, "bgm", {T_ARGS, T_DWORD, T_NONE}},
    {OP_ENABLE, "enable", {T_ARGS, T_DWORD, T_NONE}},
    {OP_DISABLE, "disable", {T_ARGS, T_DWORD, T_NONE}},
    {OP_WINDOW_MSG, "window_msg", {T_ARGS, T_STR, T_NONE}},
    {OP_ADD_MSG, "add_msg", {T_ARGS, T_STR, T_NONE}},
    {OP_MESEND, "mesend", {T_NONE, T_NONE}},
    {OP_GETTIME, "gettime", {T_IMED, T_REG, T_NONE}},
    {OP_WINEND, "winend", {T_NONE, T_NONE}},
    {OP_NPC_CRT_V1, "npc_crt_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_NPC_CRT_V3, "npc_crt_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_NPC_STOP, "npc_stop", {T_ARGS, T_DWORD, T_NONE}},
    {OP_NPC_PLAY, "npc_play", {T_ARGS, T_DWORD, T_NONE}},
    {OP_NPC_KILL, "npc_kill", {T_ARGS, T_DWORD, T_NONE}},
    {OP_NPC_NONT, "npc_nont", {T_NONE, T_NONE}},
    {OP_NPC_TALK, "npc_talk", {T_NONE, T_NONE}},
    {OP_NPC_CRP_V1, "npc_crp_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_NPC_CRP_V3, "npc_crp_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_CREATE_PIPE, "create_pipe", {T_ARGS, T_DWORD, T_NONE}},
    {OP_P_HPSTAT_V1, "p_hpstat_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_P_HPSTAT_V3, "p_hpstat_V3", {T_ARGS, T_BREG, T_DWORD, T_NONE, T_V3}},
    {OP_P_DEAD_V1, "p_dead_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_P_DEAD_V3, "p_dead_V3", {T_ARGS, T_BREG, T_REG, T_NONE, T_V3}},
    {OP_P_DISABLEWARP, "p_disablewarp", {T_NONE, T_NONE}},
    {OP_P_ENABLEWARP, "p_enablewarp", {T_NONE, T_NONE}},
    {OP_P_MOVE_V1, "p_move_v1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_P_MOVE_V3, "p_move_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_P_LOOK, "p_look", {T_ARGS, T_DWORD, T_NONE}},
    {OP_P_ACTION_DISABLE, "p_action_disable", {T_NONE, T_NONE}},
    {OP_P_ACTION_ENABLE, "p_action_enable", {T_NONE, T_NONE}},
    {OP_DISABLE_MOVEMENT1, "disable_movement1", {T_ARGS, T_DWORD, T_NONE}},
    {OP_ENABLE_MOVEMENT1, "enable_movement1", {T_ARGS, T_DWORD, T_NONE}},
    {OP_P_NONCOL, "p_noncol", {T_NONE, T_NONE}},
    {OP_P_COL, "p_col", {T_NONE, T_NONE}},
    {OP_P_SETPOS, "p_setpos", {T_ARGS, T_DWORD, T_BREG, T_NONE}},
    {OP_P_RETURN_GUILD, "p_return_guild", {T_NONE, T_NONE}},
    {OP_P_TALK_GUILD, "p_talk_guild", {T_ARGS, T_DWORD, T_NONE}},
    {OP_NPC_TALK_PL_V1, "npc_talk_pl_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_NPC_TALK_PL_V3, "npc_talk_pl_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_NPC_TALK_KILL, "npc_talk_kill", {T_ARGS, T_DWORD, T_NONE}},
    {OP_NPC_CRTPK_V1, "npc_crtpk_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_NPC_CRTPK_V3, "npc_crtpk_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_NPC_CRPPK_V1, "npc_crppk_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_NPC_CRPPK_V3, "npc_crppk_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_NPC_CRPTALK_V1, "npc_crptalk_v1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_NPC_CRPTALK_V3, "npc_crptalk_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_P_LOOK_AT, "p_look_at", {T_ARGS, T_DWORD, T_DWORD, T_NONE}},
    {OP_NPC_CRP_ID_V1, "npc_crp_id_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_NPC_CRP_ID_V3, "npc_crp_id_v3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_CAM_QUAKE, "cam_quake", {T_NONE, T_NONE}},
    {OP_CAM_ADJ, "cam_adj", {T_NONE, T_NONE}},
    {OP_CAM_ZMIN, "cam_zmin", {T_NONE, T_NONE}},
    {OP_CAM_ZMOUT, "cam_zmout", {T_NONE, T_NONE}},
    {OP_CAM_PAN_V1, "cam_pan_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_CAM_PAN_V3, "cam_pan_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_GAME_LEV_SUPER, "game_lev_super", {T_NONE, T_NONE}},
    {OP_GAME_LEV_RESET, "game_lev_reset", {T_NONE, T_NONE}},
    {OP_POS_PIPE_V1, "pos_pipe_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_POS_PIPE_V3, "pos_pipe_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_IF_ZONE_CLEAR, "if_zone_clear", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_CHK_ENE_NUM, "chk_ene_num", {T_IMED, T_REG, T_NONE}},
    {OP_UNHIDE_OBJ, "unhide_obj", {T_IMED, T_REG, T_NONE}},
    {OP_UNHIDE_ENE, "unhide_ene", {T_IMED, T_REG, T_NONE}},
    {OP_AT_COORDS_CALL, "at_coords_call", {T_IMED, T_REG, T_NONE}},
    {OP_AT_COORDS_TALK, "at_coords_talk", {T_IMED, T_REG, T_NONE}},
    {OP_COL_NPCIN, "col_npcin", {T_IMED, T_REG, T_NONE}},
    {OP_COL_NPCINR, "col_npcinr", {T_IMED, T_REG, T_NONE}},
    {OP_SWITCH_ON, "switch_on", {T_ARGS, T_DWORD, T_NONE}},
    {OP_SWITCH_OFF, "switch_off", {T_ARGS, T_DWORD, T_NONE}},
    {OP_PLAYBGM_EPI, "playbgm_epi", {T_ARGS, T_DWORD, T_NONE}},
    {OP_SET_MAINWARP, "set_mainwarp", {T_ARGS, T_DWORD, T_NONE}},
    {OP_SET_OBJ_PARAM, "set_obj_param", {T_IMED, T_REG, T_BREG, T_NONE}},
    {OP_SET_FLOOR_HANDLER, "set_floor_handler", {T_ARGS, T_DWORD, T_FUNC2, T_NONE}},
    {OP_CLR_FLOOR_HANDLER, "clr_floor_handler", {T_ARGS, T_DWORD, T_NONE}},
    {OP_COL_PLINAW, "col_plinaw", {T_IMED, T_REG, T_NONE}},
    {OP_HUD_HIDE, "hud_hide", {T_NONE, T_NONE}},
    {OP_HUD_SHOW, "hud_show", {T_NONE, T_NONE}},
    {OP_CINE_ENABLE, "cine_enable", {T_NONE, T_NONE}},
    {OP_CINE_DISABLE, "cine_disable", {T_NONE, T_NONE}},
    {OP_SET_QT_FAILURE, "set_qt_failure", {T_IMED, T_FUNC2, T_NONE}},
    {OP_SET_QT_SUCCESS, "set_qt_success", {T_IMED, T_FUNC2, T_NONE}},
    {OP_CLR_QT_FAILURE, "clr_qt_failure", {T_NONE, T_NONE}},
    {OP_CLR_QT_SUCCESS, "clr_qt_success", {T_NONE, T_NONE}},
    {OP_SET_QT_CANCEL, "set_qt_cancel", {T_IMED, T_FUNC2, T_NONE}},
    {OP_CLR_QT_CANCEL, "clr_qt_cancel", {T_NONE, T_NONE}},
    {OP_PL_WALK_V1, "pl_walk_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_PL_WALK_V3, "pl_walk_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_PL_ADD_MESETA, "pl_add_meseta", {T_ARGS, T_DWORD, T_DWORD, T_NONE}},
    {OP_THREAD_STG, "thread_stg", {T_IMED, T_FUNC, T_NONE}},
    {OP_DEL_OBJ_PARAM, "del_obj_param", {T_IMED, T_REG, T_NONE}},
    {OP_ITEM_CREATE, "item_create", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_ITEM_CREATE2, "item_create2", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_ITEM_DELETE, "item_delete", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_ITEM_DELETE2, "item_delete2", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_ITEM_CHECK, "item_check", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_SETEVT, "setevt", {T_ARGS, T_DWORD, T_NONE}},
    {OP_GET_DIFFLVL, "get_difflvl", {T_IMED, T_REG, T_NONE}},
    {OP_SET_QT_EXIT, "set_qt_exit", {T_IMED, T_FUNC2, T_NONE}},
    {OP_CLR_QT_EXIT, "clr_qt_exit", {T_NONE, T_NONE}},
    {OP_PARTICLE_V1, "particle_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_PARTICLE_V3, "particle_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_NPC_TEXT, "npc_text", {T_ARGS, T_DWORD, T_STR, T_NONE}},
    {OP_NPC_CHKWARP, "npc_chkwarp", {T_NONE, T_NONE}},
    {OP_PL_PKOFF, "pl_pkoff", {T_NONE, T_NONE}},
    {OP_MAP_DESIGNATE, "map_designate", {T_IMED, T_REG, T_NONE}},
    {OP_MASTERKEY_ON, "masterkey_on", {T_NONE, T_NONE}},
    {OP_MASTERKEY_OFF, "masterkey_off", {T_NONE, T_NONE}},
    {OP_WINDOW_TIME, "window_time", {T_NONE, T_NONE}},
    {OP_WINEND_TIME, "winend_time", {T_NONE, T_NONE}},
    {OP_WINSET_TIME, "winset_time", {T_IMED, T_REG, T_NONE}},
    {OP_GETMTIME, "getmtime", {T_IMED, T_REG, T_NONE}},
    {OP_SET_QUEST_BOARD_HANDLER, "set_quest_board_handler", {T_ARGS, T_DWORD, T_FUNC2, T_STR, T_NONE}},
    {OP_CLEAR_QUEST_BOARD_HANDLER, "clear_quest_board_handler", {T_ARGS, T_DWORD, T_NONE}},
    {OP_PARTICLE_ID_V1, "particle_id_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_PARTICLE_ID_V3, "particle_id_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_NPC_CRPTALK_ID_V1, "npc_crptalk_id_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_NPC_CRPTALK_ID_V3, "npc_crptalk_id_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_NPC_LANG_CLEAN, "npc_lang_clean", {T_NONE, T_NONE}},
    {OP_PL_PKON, "pl_pkon", {T_NONE, T_NONE}},
    {OP_PL_CHK_ITEM2, "pl_chk_item2", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_ENABLE_MAINMENU, "enable_mainmenu", {T_NONE, T_NONE}},
    {OP_DISABLE_MAINMENU, "disable_mainmenu", {T_NONE, T_NONE}},
    {OP_START_BATTLEBGM, "start_battlebgm", {T_NONE, T_NONE}},
    {OP_END_BATTLEBGM, "end_battlebgm", {T_NONE, T_NONE}},
    {OP_DISP_MSG_QB, "disp_msg_qb", {T_ARGS, T_STR, T_NONE}},
    {OP_CLOSE_MSG_QB, "close_msg_qb", {T_NONE, T_NONE}},
    {OP_SET_EVENTFLAG_V1, "set_eventflag_v1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_SET_EVENTFLAG_V3, "set_eventflag_v3", {T_ARGS, T_DWORD, T_DWORD, T_NONE}},
    {OP_SYNC_LETI, "sync_leti", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_SET_RETURNHUNTER, "set_returnhunter", {T_NONE, T_NONE}},
    {OP_SET_RETURNCITY, "set_returncity", {T_NONE, T_NONE}},
    {OP_LOAD_PVR, "load_pvr", {T_NONE, T_NONE}},
    {OP_LOAD_MIDI, "load_midi", {T_NONE, T_NONE}},
    {OP_UNKNOWNDE, "unknownDE", {T_IMED, T_REG, T_NONE}},
    {OP_NPC_PARAM_V1, "npc_param_V1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_NPC_PARAM_V3, "npc_param_V3", {T_ARGS, T_BREG, T_DWORD, T_NONE, T_V3}},
    {OP_PAD_DRAGON, "pad_dragon", {T_NONE, T_NONE}},
    {OP_CLEAR_MAINWARP, "clear_mainwarp", {T_ARGS, T_DWORD, T_NONE}},
    {OP_PCAM_PARAM_V1, "pcam_param_V1", {T_DC, T_DREG, T_NONE}},
    {OP_PCAM_PARAM_V3, "pcam_param_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_START_SETEVT_V1, "start_setevt_v1", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_START_SETEVT_V3, "start_setevt_v3", {T_ARGS, T_BREG, T_DWORD, T_NONE}},
    {OP_WARP_ON, "warp_on", {T_NONE, T_NONE}},
    {OP_WARP_OFF, "warp_off", {T_NONE, T_NONE}},
    {OP_GET_SLOTNUMBER, "get_slotnumber", {T_IMED, T_REG, T_NONE}},
    {OP_GET_SERVERNUMBER, "get_servernumber", {T_IMED, T_REG, T_NONE}},
    {OP_SET_EVENTFLAG2, "set_eventflag2", {T_ARGS, T_DWORD, T_REG, T_NONE}},
    {OP_RES, "res", {T_IMED, T_REG, T_REG, T_NONE}},
    {OP_UNKNOWNEA, "unknownEA", {T_IMED, T_REG, T_DWORD, T_NONE}},
    {OP_ENABLE_BGMCTRL, "enable_bgmctrl", {T_ARGS, T_DWORD, T_NONE}},
    {OP_SW_SEND, "sw_send", {T_IMED, T_REG, T_NONE}},
    {OP_CREATE_BGMCTRL, "create_bgmctrl", {T_NONE, T_NONE}},
    {OP_PL_ADD_MESETA2, "pl_add_meseta2", {T_ARGS, T_DWORD, T_NONE}},
    {OP_SYNC_LET, "sync_let", {T_DC, T_DREG, T_DREG, T_NONE}},
    {OP_SYNC_REGISTER, "sync_register", {T_ARGS, T_BREG, T_DWORD, T_NONE, T_V3}},
    {OP_SYNC_REGISTER2, "sync_register2", {T_ARGS, T_BREG, T_REG, T_NONE, T_V3}},
    {OP_SEND_REGWORK, "send_regwork", {T_DC, T_DREG, T_DWORD, T_NONE}},
    {OP_LETI_FIXED_CAMERA_V1, "leti_fixed_camera_V1", {T_DC, T_DREG, T_NONE}},
    {OP_LETI_FIXED_CAMERA_V3, "leti_fixed_camera_V3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_DEFAULT_CAMERA_POS1, "default_camera_pos1", {T_NONE, T_NONE}},
    {OP_UNKNOWNF8, "unknownF8", {T_IMED, T_REG, T_NONE}},
    {OP_GET_GC_NUMBER, "get_gc_number", {T_IMED, T_REG, T_NONE}},
    {OP_UNKNOWNFB, "unknownFB", {T_IMED, T_DATA, T_NONE}},
    {OP_SET_CHAT_CALLBACK, "set_chat_callback?", {T_ARGS, T_BREG, T_STR, T_NONE, T_V2}},
    {OP_GET_DIFFLVL2, "get_difflvl2", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_GET_NUMBER_OF_PLAYER1, "get_number_of_player1", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_GET_COORD_OF_PLAYER, "get_coord_of_player", {T_IMED, T_REG, T_REG, T_NONE, T_V2}},
    {OP_ENABLE_MAP, "enable_map", {T_NONE, T_NONE, T_V2}},
    {OP_DISABLE_MAP, "disable_map", {T_NONE, T_NONE, T_V2}},
    {OP_MAP_DESIGNATE_EX, "map_designate_ex", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF80E, "unknownF80E", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF80F, "unknownF80F", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_BA_INITIAL_FLOOR, "ba_initial_floor", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_SET_BA_RULES, "set_ba_rules", {T_NONE, T_NONE, T_V2}},
    {OP_UNKNOWNF812, "unknownF812", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF813, "unknownF813", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF814, "unknownF814", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF815, "unknownF815", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF816, "unknownF816", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF817, "unknownF817", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF818, "unknownF818", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF819, "unknownF819", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF81A, "unknownF81A", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF81B, "unknownF81B", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_BA_DISP_MSG, "ba_disp_msg", {T_ARGS, T_STR, T_NONE, T_V2}},
    {OP_DEATH_LVL_UP, "death_lvl_up", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_DEATH_TECH_LVL_UP, "death_tech_lvl_up", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_CMODE_STAGE, "cmode_stage", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF823, "unknownF823", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF824, "unknownF824", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_EXP_MULTIPLICATION, "exp_multiplication", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_EXP_DIVISION, "exp_division?", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_GET_USER_IS_DEAD, "get_user_is_dead?", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_GO_FLOOR, "go_floor", {T_IMED, T_REG, T_REG, T_NONE, T_V2}},
    {OP_UNLOCK_DOOR2, "unlock_door2", {T_ARGS, T_DWORD, T_DWORD, T_NONE, T_V2}},
    {OP_LOCK_DOOR2, "lock_door2", {T_ARGS, T_DWORD, T_DWORD, T_NONE, T_V2}},
    {OP_IF_SWITCH_NOT_PRESSED, "if_switch_not_pressed", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_IF_SWITCH_PRESSED, "if_switch_pressed", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF82F, "unknownF82F", {T_ARGS, T_DWORD, T_DWORD, T_NONE, T_V2}},
    {OP_CONTROL_DRAGON, "control_dragon", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_RELEASE_DRAGON, "release_dragon", {T_NONE, T_NONE, T_V2}},
    {OP_SHRINK, "shrink", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNSHRINK, "unshrink", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_DISPLAY_CLOCK2, "display_clock2?", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF83D, "unknownF83D", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_DELETE_AREA_TITLE, "delete_area_title?", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_LOAD_NPC_DATA, "load_npc_data", {T_NONE, T_NONE, T_V2}},
    {OP_GET_NPC_DATA, "get_npc_data", {T_IMED, T_DATA, T_NONE, T_V2}},
    {OP_GIVE_DAMAGE_SCORE, "give_damage_score", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_TAKE_DAMAGE_SCORE, "take_damage_score", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNK_SCORE_F84A, "unk_score_F84A", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNK_SCORE_F84B, "unk_score_F84B", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_KILL_SCORE, "kill_score", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_DEATH_SCORE, "death_score", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNK_SCORE_F84E, "unk_score_F84E", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_ENEMY_DEATH_SCORE, "enemy_death_score", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_MESETA_SCORE, "meseta_score", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF851, "unknownF851", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF852, "unknownF852", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_REVERSE_WARPS, "reverse_warps", {T_NONE, T_NONE, T_V2}},
    {OP_UNREVERSE_WARPS, "unreverse_warps", {T_NONE, T_NONE, T_V2}},
    {OP_SET_ULT_MAP, "set_ult_map", {T_NONE, T_NONE, T_V2}},
    {OP_UNSET_ULT_MAP, "unset_ult_map", {T_NONE, T_NONE, T_V2}},
    {OP_SET_AREA_TITLE, "set_area_title", {T_ARGS, T_STR, T_NONE, T_V2}},
    {OP_UNKNOWNF858, "unknownF858", {T_NONE, T_NONE, T_V2}},
    {OP_EQUIP_ITEM_V2, "equip_item_v2", {T_DC, T_DREG, T_NONE, T_V2}},
    {OP_EQUIP_ITEM_V3, "equip_item_v3", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_UNEQUIP_ITEM_V2, "unequip_item_V2", {T_DC, T_DREG, T_DWORD, T_NONE, T_V2}},
    {OP_UNEQUIP_ITEM_V3, "unequip_item_V3", {T_ARGS, T_DWORD, T_DWORD, T_NONE, T_V3}},
    {OP_BA_SHOW_SELF_TRAPS, "BA_Show_Self_Traps", {T_NONE}},
    {OP_BA_HIDE_SELF_TRAPS, "BA_Hide_Self_Traps", {T_NONE}},
    {OP_UNKNOWNF85E, "unknownF85E", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF85F, "unknownF85F", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF860, "unknownF860", {T_NONE, T_NONE, T_V2}},
    {OP_UNKNOWNF861, "unknownF861", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_CMODE_RANK, "cmode_rank", {T_ARGS, T_DWORD, T_STR, T_NONE, T_V2}},
    {OP_AWARD_ITEM_NAME, "award_item_name?", {T_NONE, T_NONE, T_V2}},
    {OP_AWARD_ITEM_SELECT, "award_item_select?", {T_NONE, T_NONE, T_V2}},
    {OP_AWARD_ITEM_GIVE_TO, "award_item_give_to?", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF868, "unknownF868", {T_IMED, T_REG, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF869, "unknownF869", {T_IMED, T_REG, T_REG, T_NONE, T_V2}},
    {OP_ITEM_CREATE_CMODE, "item_create_cmode", {T_IMED, T_REG, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF86B, "unknownF86B", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_AWARD_ITEM_OK, "award_item_ok?", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF86D, "unknownF86D", {T_NONE, T_NONE, T_V2}},
    {OP_UNKNOWNF86E, "unknownF86E", {T_NONE, T_NONE, T_V2}},
    {OP_BA_SET_LIVES, "ba_set_lives", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_BA_SET_TECH_LVL, "ba_set_tech_lvl", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_BA_SET_LVL, "ba_set_lvl", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_BA_SET_TIME_LIMIT, "ba_set_time_limit", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_BOSS_IS_DEAD, "boss_is_dead?", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_ENABLE_TECHS, "enable_techs", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_DISABLE_TECHS, "disable_techs", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_GET_GENDER, "get_gender", {T_IMED, T_REG, T_REG, T_NONE, T_V2}},
    {OP_GET_CHARA_CLASS, "get_chara_class", {T_IMED, T_REG, T_REG, T_NONE, T_V2}},
    {OP_TAKE_SLOT_MESETA, "take_slot_meseta", {T_IMED, T_REG, T_REG, T_NONE, T_V2}},
    {OP_READ_GUILDCARD_FLAG, "read_guildcard_flag", {T_IMED, T_REG, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF880, "unknownF880", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_GET_PL_NAME, "get_pl_name?", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF883, "unknownF883", {T_IMED, T_REG, T_REG, T_NONE, T_V2}},
    {OP_BA_CLOSE_MSG, "ba_close_msg", {T_NONE, T_NONE, T_V2}},
    {OP_GET_PLAYER_STATUS, "get_player_status", {T_IMED, T_REG, T_REG, T_NONE, T_V2}},
    {OP_SEND_MAIL, "send_mail", {T_ARGS, T_BREG, T_STR, T_NONE, T_V2}},
    {OP_GET_GAME_VERSION, "get_game_version", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_CHL_SET_TIMERECORD, "chl_set_timerecord?", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_CHL_GET_TIMERECORD, "chl_get_timerecord?", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF88F, "unknownF88F", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF890, "unknownF890", {T_NONE, T_NONE, T_V2}},
    {OP_LOAD_ENEMY_DATA, "load_enemy_data", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_GET_PHYSICAL_DATA, "get_physical_data", {T_IMED, T_DATA, T_NONE, T_V2}},
    {OP_GET_ATTACK_DATA, "get_attack_data", {T_IMED, T_DATA, T_NONE, T_V2}},
    {OP_GET_RESIST_DATA, "get_resist_data", {T_IMED, T_DATA, T_NONE, T_V2}},
    {OP_GET_MOVEMENT_DATA, "get_movement_data", {T_IMED, T_DATA, T_NONE, T_V2}},
    {OP_SHIFT_LEFT, "shift_left", {T_IMED, T_REG, T_REG, T_NONE, T_V2}},
    {OP_SHIFT_RIGHT, "shift_right", {T_IMED, T_REG, T_REG, T_NONE, T_V2}},
    {OP_GET_RANDOM, "get_random", {T_IMED, T_REG, T_REG, T_NONE, T_V2}},
    {OP_RESET_MAP, "reset_map", {T_NONE, T_NONE, T_V2}},
    {OP_DISP_CHL_RETRY_MNU, "disp_chl_retry_mnu", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_CHL_REVERSER, "chl_reverser?", {T_NONE, T_NONE, T_V2}},
    {OP_UNKNOWNF89E, "unknownF89E", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF89F, "unknownF89F", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF8A0, "unknownF8A0", {T_NONE, T_NONE, T_V2}},
    {OP_UNKNOWNF8A1, "unknownF8A1", {T_NONE, T_NONE, T_V2}},
    {OP_UNKNOWNF8A8, "unknownF8A8", {T_ARGS, T_DWORD, T_NONE, T_V2}},
    {OP_UNKNOWNF8A9, "unknownF8A9", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_GET_NUMBER_OF_PLAYER2, "get_number_of_player2", {T_IMED, T_REG, T_NONE, T_V2}},
    {OP_UNKNOWNF8B8, "unknownF8B8", {T_NONE, T_NONE, T_V2}},
    {OP_CHL_RECOVERY, "chl_recovery?", {T_NONE, T_NONE, T_V2}},
    {OP_SET_EPISODE, "set_episode", {T_IMED, T_DWORD, T_NONE, T_V3}},
    {OP_FILE_DL_REQ, "file_dl_req", {T_ARGS, T_DWORD, T_STR, T_NONE, T_V3}},
    {OP_GET_DL_STATUS, "get_dl_status", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_GBA_UNKNOWN4, "gba_unknown4?", {T_NONE, T_NONE, T_V3}},
    {OP_GET_GBA_STATE, "get_gba_state?", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_UNKNOWNF8C4, "unknownF8C4", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_UNKNOWNF8C5, "unknownF8C5", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_QEXIT, "QEXIT", {T_NONE, T_NONE, T_V3}},
    {OP_USE_ANIMATION, "use_animation", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_STOP_ANIMATION, "stop_animation", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_RUN_TO_COORD, "run_to_coord", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_SET_SLOT_INVINCIBLE, "set_slot_invincible", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_UNKNOWNF8CB, "unknownF8CB", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_SET_SLOT_POISON, "set_slot_poison", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_SET_SLOT_PARALYSE, "set_slot_paralyse", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_SET_SLOT_SHOCK, "set_slot_shock", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_SET_SLOT_FREEZE, "set_slot_freeze", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_SET_SLOT_SLOW, "set_slot_slow", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_SET_SLOT_CONFUSE, "set_slot_confuse", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_SET_SLOT_SHIFTA, "set_slot_shifta", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_SET_SLOT_DEBAND, "set_slot_deband", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_SET_SLOT_JELLEN, "set_slot_jellen", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_SET_SLOT_ZALURE, "set_slot_zalure", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_FLETI_FIXED_CAMERA, "fleti_fixed_camera", {T_ARGS, T_BREG, T_NONE, T_V3}},
    {OP_FLETI_LOCKED_CAMERA, "fleti_locked_camera", {T_ARGS, T_DWORD, T_BREG, T_NONE, T_V3}},
    {OP_DEFAULT_CAMERA_POS2, "default_camera_pos2", {T_NONE, T_NONE, T_V3}},
    {OP_SET_MOTION_BLUR, "set_motion_blur", {T_NONE, T_NONE, T_V3}},
    {OP_SET_SCREEN_BW, "set_screen_b&w", { T_NONE, T_NONE, T_V3}},
    {OP_UNKNOWNF8DB, "unknownF8DB", {T_ARGS, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_BREG, T_FUNC, T_NONE, T_V3}},
    {OP_NPC_ACTION_STRING, "NPC_action_string", {T_IMED, T_REG, T_REG, T_STRDATA, T_NONE, T_V3}},
    {OP_GET_PAD_COND, "get_pad_cond", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_GET_BUTTON_COND, "get_button_cond", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_FREEZE_ENEMIES, "freeze_enemies", {T_NONE, T_NONE, T_V3}},
    {OP_UNFREEZE_ENEMIES, "unfreeze_enemies", {T_NONE, T_NONE, T_V3}},
    {OP_FREEZE_EVERYTHING, "freeze_everything", {T_NONE, T_NONE, T_V3}},
    {OP_UNFREEZE_EVERYTHING, "unfreeze_everything", {T_NONE, T_NONE, T_V3}},
    {OP_RESTORE_HP, "restore_hp", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_RESTORE_TP, "restore_tp", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_CLOSE_CHAT_BUBBLE, "close_chat_bubble", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_UNKNOWNF8E6, "unknownF8E6", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_UNKNOWNF8E7, "unknownF8E7", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_UNKNOWNF8E8, "unknownF8E8", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_UNKNOWNF8E9, "unknownF8E9", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_UNKNOWNF8EA, "unknownF8EA", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_UNKNOWNF8EB, "unknownF8EB", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_UNKNOWNF8EC, "unknownF8EC", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_ANIMATION_CHECK, "animation_check", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_CALL_IMAGE_DATA, "call_image_data", {T_ARGS, T_DWORD, T_DATA, T_NONE, T_V3}},
    {OP_UNKNOWNF8EF, "unknownF8EF", {T_NONE, T_NONE, T_V3}},
    {OP_TURN_OFF_BGM_P2, "turn_off_bgm_p2", {T_NONE, T_NONE, T_V3}},
    {OP_TURN_ON_BGM_P2, "turn_on_bgm_p2", {T_NONE, T_NONE, T_V3}},
    {OP_LOAD_UNK_DATA, "load_unk_data", {T_ARGS, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_BREG, T_DATA, T_NONE, T_V3}},
    {OP_PARTICLE2, "particle2", {T_ARGS, T_BREG, T_REG, T_REG, T_NONE, T_V3}},
    {OP_DEC2FLOAT, "dec2float", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_FLOAT2DEC, "float2dec", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_FLET, "flet", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_FLETI, "fleti", {T_IMED, T_REG, T_FLOAT, T_NONE, T_V3}},
    {OP_FADD, "fadd", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_FADDI, "faddi", {T_IMED, T_REG, T_FLOAT, T_NONE, T_V3}},
    {OP_FSUB, "fsub", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_FSUBI, "fsubi", {T_IMED, T_REG, T_FLOAT, T_NONE, T_V3}},
    {OP_FMUL, "fmul", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_FMULI, "fmuli", {T_IMED, T_REG, T_FLOAT, T_NONE, T_V3}},
    {OP_FDIV, "fdiv", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_FDIVI, "fdivi", {T_IMED, T_REG, T_FLOAT, T_NONE, T_V3}},
    {OP_GET_UNKNOWN_COUNT, "get_unknown_count?", {T_ARGS, T_DWORD, T_BREG, T_NONE, T_V3}},
    {OP_GET_STACKABLE_ITEM_COUNT, "get_stackable_item_count", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_FREEZE_AND_HIDE_EQUIP, "freeze_and_hide_equip", {T_NONE, T_NONE, T_V3}},
    {OP_THAW_AND_SHOW_EQUIP, "thaw_and_show_equip", {T_NONE, T_NONE, T_V3}},
    {OP_SET_PALETTEX_CALLBACK, "set_paletteX_callback", {T_ARGS, T_REG, T_FUNC2, T_NONE, T_V3}},
    {OP_ACTIVATE_PALETTEX, "activate_paletteX", {T_ARGS, T_REG, T_NONE, T_V3}},
    {OP_ENABLE_PALETTEX, "enable_paletteX", {T_ARGS, T_REG, T_NONE, T_V3}},
    {OP_RESTORE_PALETTEX, "restore_paletteX", {T_ARGS, T_DWORD, T_NONE, T_V3}},
    {OP_DISABLE_PALETTEX, "disable_paletteX", {T_ARGS, T_DWORD, T_NONE, T_V3}},
    {OP_GET_PALETTEX_ACTIVATED, "get_paletteX_activated", {T_ARGS, T_DWORD, T_BREG, T_NONE, T_V3}},
    {OP_GET_UNKNOWN_PALETTEX_STATUS, "get_unknown_paletteX_status?", {T_ARGS, T_DWORD, T_BREG, T_NONE, T_V3}},
    {OP_DISABLE_MOVEMENT2, "disable_movement2", {T_ARGS, T_REG, T_NONE, T_V3}},
    {OP_ENABLE_MOVEMENT2, "enable_movement2", {T_ARGS, T_REG, T_NONE, T_V3}},
    {OP_GET_TIME_PLAYED, "get_time_played", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_GET_GUILDCARD_TOTAL, "get_guildcard_total", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_GET_SLOT_MESETA, "get_slot_meseta", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_GET_PLAYER_LEVEL, "get_player_level", {T_ARGS, T_DWORD, T_BREG, T_NONE, T_V3}},
    {OP_GET_SECTION_ID, "get_Section_ID", {T_ARGS, T_DWORD, T_BREG, T_NONE, T_V3}},
    {OP_GET_PLAYER_HP, "get_player_hp", {T_ARGS, T_REG, T_BREG, T_NONE, T_V3}},
    {OP_GET_FLOOR_NUMBER, "get_floor_number", {T_ARGS, T_REG, T_BREG, T_NONE, T_V3}},
    {OP_GET_COORD_PLAYER_DETECT, "get_coord_player_detect", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_READ_GLOBAL_FLAG, "read_global_flag", {T_ARGS, T_DWORD, T_BREG, T_NONE, T_V3}},
    {OP_WRITE_GLOBAL_FLAG, "write_global_flag", {T_ARGS, T_DWORD, T_REG, T_NONE, T_V3}},
    {OP_UNKNOWNF927, "unknownF927", {T_IMED, T_REG, T_REG, T_NONE, T_V3}},
    {OP_FLOOR_PLAYER_DETECT, "floor_player_detect", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_READ_DISK_FILE, "read_disk_file?", {T_ARGS, T_STR, T_NONE, T_V3}},
    {OP_OPEN_PACK_SELECT, "open_pack_select", {T_NONE, T_NONE, T_V3}},
    {OP_ITEM_SELECT, "item_select", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_GET_ITEM_ID, "get_item_id", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_COLOR_CHANGE, "color_change", {T_ARGS, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_NONE, T_V3}},
    {OP_SEND_STATISTIC, "send_statistic?", {T_ARGS, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_NONE, T_V3}},
    {OP_UNKNOWNF92F, "unknownF92F", {T_ARGS, T_DWORD, T_DWORD, T_NONE, T_V3}},
    {OP_CHAT_BOX, "chat_box", {T_ARGS, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_STR, T_NONE, T_V3}},
    {OP_CHAT_BUBBLE, "chat_bubble", {T_ARGS, T_DWORD, T_STR, T_NONE, T_V3}},
    {OP_UNKNOWNF933, "unknownF933", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_SCROLL_TEXT, "scroll_text", {T_ARGS, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_FLOAT, T_BREG, T_STR, T_NONE, T_V3}},
    {OP_GBA_UNKNOWN1, "gba_unknown1", {T_NONE, T_NONE, T_V3}},
    {OP_GBA_UNKNOWN2, "gba_unknown2", {T_NONE, T_NONE, T_V3}},
    {OP_GBA_UNKNOWN3, "gba_unknown3", {T_NONE, T_NONE, T_V3}},
    {OP_ADD_DAMAGE_TO, "add_damage_to?", {T_ARGS, T_DWORD, T_DWORD, T_NONE, T_V3}},
    {OP_ITEM_DELETE2, "item_delete2", {T_ARGS, T_DWORD, T_NONE, T_V3}},
    {OP_GET_ITEM_INFO, "get_item_info", {T_ARGS, T_DWORD, T_BREG, T_NONE, T_V3}},
    {OP_ITEM_PACKING1, "item_packing1", {T_ARGS, T_DWORD, T_NONE, T_V3}},
    {OP_ITEM_PACKING2, "item_packing2", {T_ARGS, T_DWORD, T_DWORD, T_NONE, T_V3}},
    {OP_GET_LANG_SETTING, "get_lang_setting?", {T_ARGS, T_BREG, T_NONE, T_V3}},
    {OP_PREPARE_STATISTIC, "prepare_statistic?", {T_ARGS, T_DWORD, T_FUNC, T_FUNC, T_NONE, T_V3}},
    {OP_KEYWORD_DETECT, "keyword_detect", {T_NONE, T_NONE, T_V3}},
    {OP_KEYWORD, "Keyword", {T_ARGS, T_BREG, T_DWORD, T_STR, T_NONE, T_V3}},
    {OP_GET_GUILDCARD_NUM, "get_guildcard_num", {T_ARGS, T_DWORD, T_BREG, T_NONE, T_V3}},
    {OP_GET_WRAP_STATUS, "get_wrap_status", {T_ARGS, T_DWORD, T_BREG, T_NONE, T_V3}},
    {OP_INITIAL_FLOOR, "initial_floor", {T_ARGS, T_DWORD, T_NONE, T_V3}},
    {OP_SIN, "sin", {T_ARGS, T_BREG, T_DWORD, T_NONE, T_V3}},
    {OP_COS, "cos", {T_ARGS, T_BREG, T_DWORD, T_NONE, T_V3}},
    {OP_BOSS_IS_DEAD2, "boss_is_dead2?", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_UNKNOWNF94B, "unknownF94B", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_UNKNOWNF94C, "unknownF94C", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_IS_THERE_CARDBATTLE, "is_there_cardbattle?", {T_IMED, T_REG, T_NONE, T_V3}},
    {OP_BB_P2_MENU, "BB_p2_menu", {T_ARGS, T_DWORD, T_NONE, T_V4}},
    {OP_BB_MAP_DESIGNATE, "BB_Map_Designate", {T_IMED, T_BYTE, T_WORD, T_BYTE, T_BYTE, T_NONE, T_V4}},
    {OP_BB_GET_NUMBER_IN_PACK, "BB_get_number_in_pack", {T_IMED, T_REG, T_NONE, T_V4}},
    {OP_BB_SWAP_ITEM, "BB_swap_item", {T_ARGS, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_DWORD, T_FUNC2, T_FUNC2, T_NONE, T_V4}},
    {OP_BB_CHECK_WRAP, "BB_check_wrap", {T_ARGS, T_REG, T_BREG, T_NONE, T_V4}},
    {OP_BB_EXCHANGE_PD_ITEM, "BB_exchange_PD_item", {T_ARGS, T_REG, T_REG, T_REG, T_FUNC2, T_FUNC2, T_NONE, T_V4}},
    {OP_BB_EXCHANGE_PD_SRANK, "BB_exchange_PD_srank", {T_ARGS, T_REG, T_REG, T_REG, T_REG, T_REG, T_FUNC2, T_FUNC2, T_NONE, T_V4}},
    {OP_BB_EXCHANGE_PD_SPECIAL, "BB_exchange_PD_special", {T_ARGS, T_REG, T_REG, T_REG, T_REG, T_REG, T_DWORD, T_FUNC2, T_FUNC2, T_NONE, T_V4}},
    {OP_BB_EXCHANGE_PD_PERCENT, "BB_exchange_PD_percent", {T_ARGS, T_REG, T_REG, T_REG, T_REG, T_REG, T_DWORD, T_FUNC2, T_FUNC2, T_NONE, T_V4}},
    {OP_UNKNOWNF959, "unknownF959", {T_ARGS, T_DWORD, T_NONE, T_V4}},
    {OP_BB_EXCHANGE_SLT, "BB_exchange_SLT", {T_ARGS, T_DWORD, T_BREG, T_FUNC2, T_FUNC2, T_NONE, T_V4}},
    {OP_BB_EXCHANGE_PC, "BB_exchange_PC", {T_NONE, T_NONE, T_V4}},
    {OP_BB_BOX_CREATE_BP, "BB_box_create_BP", {T_ARGS, T_DWORD, T_FLOAT, T_FLOAT, T_NONE, T_V4}},
    {OP_BB_EXCHAGE_PT, "BB_exchage_PT", {T_ARGS, T_BREG, T_BREG, T_DWORD, T_FUNC2, T_FUNC2, T_NONE, T_V4}},
    {OP_UNKNOWNF960, "unknownF960", {T_ARGS, T_REG, T_NONE, T_V4}},
    {OP_UNKNOWNF961, "unknownF961", {T_IMED, T_REG, T_NONE, T_V4}}
};

const OpcodeDefinition* get_opcode_definition(Opcode opcode) {
    for (size_t i = 0; i < NUM_OPCODES; i++) {
        if (opcodes[i].opcode == opcode) {
            return &opcodes[i];
        }
    }

    return NULL;
}

bool is_variable_sized(ParameterType type) {
    return parameter_sizes[type] == VARIABLE_SIZED;
}

size_t get_parameter_size(ParameterType type) {
    return (size_t) parameter_sizes[type];
}
